version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.${COMPUTE_UNIT}
    container_name: openai_fastapi_container
    environment:
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_ENDPOINT: ${OPENAI_API_ENDPOINT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION}
      HF_ACCESS_TOKEN: ${HF_ACCESS_TOKEN}
      TGI_API_ENDPOINT: ${TGI_API_ENDPOINT}
    volumes:
      # - ./main.py:/app/app/main.py
      # Map the host model folder to nlp_service/model.
      - ${MODEL_DIR}:/app/app/nlp_service/model
    ports:
      - "80:8000"

  mongodb:
    image: mongo:4.4.9
    container_name: mongodb_container
    ports:
      - "127.0.0.1:27017:27017"
